name: "02 - Understanding events"
on:
    workflow_dispatch:
    push:
    pull_request:
    schedule:
      - cron: "*/5 * * * *"

jobs:
  events-info-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Trigger Event
        run: echo "My trigger event is ${{github.event_name}} event"