name: 03 - Understand Runners
on: push
jobs:
    runner-info-job:
      runs-on: ubuntu-latest
      steps:
        - name: Print Runner Details
          run: | 
            echo "Workflow is executing on a Github-hosted runner."
            echo "Runner Name: $RUNNER_NAME"
            echo "Runner OS: $RUNNER_OS"
            echo "Runner Architecture: $RUNNNER_ARCH"